// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: achievement.sql

package sqlc

import (
	"context"
)

const getAchievements = `-- name: GetAchievements :many
SELECT id, user_id, type, title, description, category, progress_current, progress_target, unlocked_at FROM achievements
WHERE user_id = $1
ORDER BY unlocked_at DESC
`

func (q *Queries) GetAchievements(ctx context.Context, userID string) ([]Achievement, error) {
	rows, err := q.db.Query(ctx, getAchievements, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Achievement
	for rows.Next() {
		var i Achievement
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Description,
			&i.Category,
			&i.ProgressCurrent,
			&i.ProgressTarget,
			&i.UnlockedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unlockAchievement = `-- name: UnlockAchievement :one
INSERT INTO achievements (user_id, type, title, description, category, progress_current, progress_target)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (user_id, type) DO UPDATE SET
    category = EXCLUDED.category,
    progress_current = EXCLUDED.progress_current,
    progress_target = EXCLUDED.progress_target
RETURNING id, user_id, type, title, description, category, progress_current, progress_target, unlocked_at
`

type UnlockAchievementParams struct {
	UserID          string `json:"user_id"`
	Type            string `json:"type"`
	Title           string `json:"title"`
	Description     string `json:"description"`
	Category        string `json:"category"`
	ProgressCurrent int32  `json:"progress_current"`
	ProgressTarget  int32  `json:"progress_target"`
}

func (q *Queries) UnlockAchievement(ctx context.Context, arg UnlockAchievementParams) (Achievement, error) {
	row := q.db.QueryRow(ctx, unlockAchievement,
		arg.UserID,
		arg.Type,
		arg.Title,
		arg.Description,
		arg.Category,
		arg.ProgressCurrent,
		arg.ProgressTarget,
	)
	var i Achievement
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.ProgressCurrent,
		&i.ProgressTarget,
		&i.UnlockedAt,
	)
	return i, err
}
