// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: achievement.sql

package sqlc

import (
	"context"
)

const getAchievements = `-- name: GetAchievements :many
SELECT id, user_id, type, title, description, unlocked_at FROM achievements
WHERE user_id = $1
ORDER BY unlocked_at DESC
`

func (q *Queries) GetAchievements(ctx context.Context, userID string) ([]Achievement, error) {
	rows, err := q.db.Query(ctx, getAchievements, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Achievement
	for rows.Next() {
		var i Achievement
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Description,
			&i.UnlockedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unlockAchievement = `-- name: UnlockAchievement :one
INSERT INTO achievements (user_id, type, title, description)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, type) DO NOTHING
RETURNING id, user_id, type, title, description, unlocked_at
`

type UnlockAchievementParams struct {
	UserID      string `json:"user_id"`
	Type        string `json:"type"`
	Title       string `json:"title"`
	Description string `json:"description"`
}

func (q *Queries) UnlockAchievement(ctx context.Context, arg UnlockAchievementParams) (Achievement, error) {
	row := q.db.QueryRow(ctx, unlockAchievement,
		arg.UserID,
		arg.Type,
		arg.Title,
		arg.Description,
	)
	var i Achievement
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.UnlockedAt,
	)
	return i, err
}
