// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cheat_day.sql

package sqlc

import (
	"context"
	"time"
)

const getCheatDaysInRange = `-- name: GetCheatDaysInRange :many
SELECT date FROM cheat_days WHERE user_id = $1 AND date BETWEEN $2 AND $3 ORDER BY date
`

type GetCheatDaysInRangeParams struct {
	UserID string    `json:"user_id"`
	Date   time.Time `json:"date"`
	Date_2 time.Time `json:"date_2"`
}

func (q *Queries) GetCheatDaysInRange(ctx context.Context, arg GetCheatDaysInRangeParams) ([]time.Time, error) {
	rows, err := q.db.Query(ctx, getCheatDaysInRange, arg.UserID, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []time.Time
	for rows.Next() {
		var date time.Time
		if err := rows.Scan(&date); err != nil {
			return nil, err
		}
		items = append(items, date)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isCheatDay = `-- name: IsCheatDay :one
SELECT EXISTS(SELECT 1 FROM cheat_days WHERE user_id = $1 AND date = $2) AS is_cheat_day
`

type IsCheatDayParams struct {
	UserID string    `json:"user_id"`
	Date   time.Time `json:"date"`
}

func (q *Queries) IsCheatDay(ctx context.Context, arg IsCheatDayParams) (bool, error) {
	row := q.db.QueryRow(ctx, isCheatDay, arg.UserID, arg.Date)
	var is_cheat_day bool
	err := row.Scan(&is_cheat_day)
	return is_cheat_day, err
}

const markCheatDay = `-- name: MarkCheatDay :exec
INSERT INTO cheat_days (user_id, date) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type MarkCheatDayParams struct {
	UserID string    `json:"user_id"`
	Date   time.Time `json:"date"`
}

func (q *Queries) MarkCheatDay(ctx context.Context, arg MarkCheatDayParams) error {
	_, err := q.db.Exec(ctx, markCheatDay, arg.UserID, arg.Date)
	return err
}

const unmarkCheatDay = `-- name: UnmarkCheatDay :exec
DELETE FROM cheat_days WHERE user_id = $1 AND date = $2
`

type UnmarkCheatDayParams struct {
	UserID string    `json:"user_id"`
	Date   time.Time `json:"date"`
}

func (q *Queries) UnmarkCheatDay(ctx context.Context, arg UnmarkCheatDayParams) error {
	_, err := q.db.Exec(ctx, unmarkCheatDay, arg.UserID, arg.Date)
	return err
}
