// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: coach.sql

package sqlc

import (
	"context"
)

const getCoachHistory = `-- name: GetCoachHistory :many
SELECT id, user_id, role, content, created_at FROM coach_messages
WHERE user_id = $1
ORDER BY created_at ASC
LIMIT 100
`

func (q *Queries) GetCoachHistory(ctx context.Context, userID string) ([]CoachMessage, error) {
	rows, err := q.db.Query(ctx, getCoachHistory, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoachMessage
	for rows.Next() {
		var i CoachMessage
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Role,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveCoachMessage = `-- name: SaveCoachMessage :one
INSERT INTO coach_messages (user_id, role, content)
VALUES ($1, $2, $3)
RETURNING id, user_id, role, content, created_at
`

type SaveCoachMessageParams struct {
	UserID  string `json:"user_id"`
	Role    string `json:"role"`
	Content string `json:"content"`
}

func (q *Queries) SaveCoachMessage(ctx context.Context, arg SaveCoachMessageParams) (CoachMessage, error) {
	row := q.db.QueryRow(ctx, saveCoachMessage, arg.UserID, arg.Role, arg.Content)
	var i CoachMessage
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Role,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}
