// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: exercise.sql

package sqlc

import (
	"context"
	"time"
)

const getExercisesByDate = `-- name: GetExercisesByDate :many
SELECT id, user_id, timestamp, name, duration_min, calories_burned, created_at FROM exercises
WHERE user_id = $1 AND timestamp::date = $2
ORDER BY timestamp
`

type GetExercisesByDateParams struct {
	UserID    string    `json:"user_id"`
	Timestamp time.Time `json:"timestamp"`
}

func (q *Queries) GetExercisesByDate(ctx context.Context, arg GetExercisesByDateParams) ([]Exercise, error) {
	rows, err := q.db.Query(ctx, getExercisesByDate, arg.UserID, arg.Timestamp)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Exercise
	for rows.Next() {
		var i Exercise
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Timestamp,
			&i.Name,
			&i.DurationMin,
			&i.CaloriesBurned,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const logExercise = `-- name: LogExercise :one
INSERT INTO exercises (user_id, timestamp, name, duration_min, calories_burned)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, timestamp, name, duration_min, calories_burned, created_at
`

type LogExerciseParams struct {
	UserID         string    `json:"user_id"`
	Timestamp      time.Time `json:"timestamp"`
	Name           string    `json:"name"`
	DurationMin    int32     `json:"duration_min"`
	CaloriesBurned int32     `json:"calories_burned"`
}

func (q *Queries) LogExercise(ctx context.Context, arg LogExerciseParams) (Exercise, error) {
	row := q.db.QueryRow(ctx, logExercise,
		arg.UserID,
		arg.Timestamp,
		arg.Name,
		arg.DurationMin,
		arg.CaloriesBurned,
	)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Timestamp,
		&i.Name,
		&i.DurationMin,
		&i.CaloriesBurned,
		&i.CreatedAt,
	)
	return i, err
}
