// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: fasting.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const breakFast = `-- name: BreakFast :exec
UPDATE user_goals SET current_fast_start = NULL, fasting_streak = $2, updated_at = NOW() WHERE user_id = $1
`

type BreakFastParams struct {
	UserID        string `json:"user_id"`
	FastingStreak *int32 `json:"fasting_streak"`
}

func (q *Queries) BreakFast(ctx context.Context, arg BreakFastParams) error {
	_, err := q.db.Exec(ctx, breakFast, arg.UserID, arg.FastingStreak)
	return err
}

const getFastingStatus = `-- name: GetFastingStatus :one
SELECT eating_window_start, current_fast_start, fasting_streak
FROM user_goals WHERE user_id = $1
`

type GetFastingStatusRow struct {
	EatingWindowStart pgtype.Time        `json:"eating_window_start"`
	CurrentFastStart  pgtype.Timestamptz `json:"current_fast_start"`
	FastingStreak     *int32             `json:"fasting_streak"`
}

func (q *Queries) GetFastingStatus(ctx context.Context, userID string) (GetFastingStatusRow, error) {
	row := q.db.QueryRow(ctx, getFastingStatus, userID)
	var i GetFastingStatusRow
	err := row.Scan(&i.EatingWindowStart, &i.CurrentFastStart, &i.FastingStreak)
	return i, err
}

const startFast = `-- name: StartFast :exec
UPDATE user_goals SET current_fast_start = NOW(), updated_at = NOW() WHERE user_id = $1
`

func (q *Queries) StartFast(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, startFast, userID)
	return err
}

const updateEatingWindow = `-- name: UpdateEatingWindow :exec
UPDATE user_goals SET eating_window_start = $2, updated_at = NOW() WHERE user_id = $1
`

type UpdateEatingWindowParams struct {
	UserID            string      `json:"user_id"`
	EatingWindowStart pgtype.Time `json:"eating_window_start"`
}

func (q *Queries) UpdateEatingWindow(ctx context.Context, arg UpdateEatingWindowParams) error {
	_, err := q.db.Exec(ctx, updateEatingWindow, arg.UserID, arg.EatingWindowStart)
	return err
}
