// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: favorites.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addFoodFavorite = `-- name: AddFoodFavorite :one
INSERT INTO food_favorites (user_id, name, calories, protein_g, carbs_g, fat_g, fiber_g, serving_size, source)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (user_id, lower(name)) DO UPDATE SET
    calories = EXCLUDED.calories,
    protein_g = EXCLUDED.protein_g,
    carbs_g = EXCLUDED.carbs_g,
    fat_g = EXCLUDED.fat_g,
    fiber_g = EXCLUDED.fiber_g,
    serving_size = EXCLUDED.serving_size,
    source = EXCLUDED.source,
    updated_at = NOW()
RETURNING id, user_id, name, calories, protein_g, carbs_g, fat_g, fiber_g, serving_size, source, use_count, created_at, updated_at
`

type AddFoodFavoriteParams struct {
	UserID      string         `json:"user_id"`
	Name        string         `json:"name"`
	Calories    int32          `json:"calories"`
	ProteinG    pgtype.Numeric `json:"protein_g"`
	CarbsG      pgtype.Numeric `json:"carbs_g"`
	FatG        pgtype.Numeric `json:"fat_g"`
	FiberG      pgtype.Numeric `json:"fiber_g"`
	ServingSize string         `json:"serving_size"`
	Source      string         `json:"source"`
}

func (q *Queries) AddFoodFavorite(ctx context.Context, arg AddFoodFavoriteParams) (FoodFavorite, error) {
	row := q.db.QueryRow(ctx, addFoodFavorite,
		arg.UserID,
		arg.Name,
		arg.Calories,
		arg.ProteinG,
		arg.CarbsG,
		arg.FatG,
		arg.FiberG,
		arg.ServingSize,
		arg.Source,
	)
	var i FoodFavorite
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Calories,
		&i.ProteinG,
		&i.CarbsG,
		&i.FatG,
		&i.FiberG,
		&i.ServingSize,
		&i.Source,
		&i.UseCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFoodFavorites = `-- name: GetFoodFavorites :many
SELECT id, user_id, name, calories, protein_g, carbs_g, fat_g, fiber_g, serving_size, source, use_count, created_at, updated_at FROM food_favorites
WHERE user_id = $1
ORDER BY use_count DESC, updated_at DESC
`

func (q *Queries) GetFoodFavorites(ctx context.Context, userID string) ([]FoodFavorite, error) {
	rows, err := q.db.Query(ctx, getFoodFavorites, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FoodFavorite
	for rows.Next() {
		var i FoodFavorite
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Calories,
			&i.ProteinG,
			&i.CarbsG,
			&i.FatG,
			&i.FiberG,
			&i.ServingSize,
			&i.Source,
			&i.UseCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopFavorites = `-- name: GetTopFavorites :many
SELECT id, user_id, name, calories, protein_g, carbs_g, fat_g, fiber_g, serving_size, source, use_count, created_at, updated_at FROM food_favorites
WHERE user_id = $1
ORDER BY use_count DESC
LIMIT $2
`

type GetTopFavoritesParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
}

func (q *Queries) GetTopFavorites(ctx context.Context, arg GetTopFavoritesParams) ([]FoodFavorite, error) {
	rows, err := q.db.Query(ctx, getTopFavorites, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FoodFavorite
	for rows.Next() {
		var i FoodFavorite
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Calories,
			&i.ProteinG,
			&i.CarbsG,
			&i.FatG,
			&i.FiberG,
			&i.ServingSize,
			&i.Source,
			&i.UseCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementFavoriteUseCount = `-- name: IncrementFavoriteUseCount :exec
UPDATE food_favorites SET use_count = use_count + 1, updated_at = NOW()
WHERE id = $1 AND user_id = $2
`

type IncrementFavoriteUseCountParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) IncrementFavoriteUseCount(ctx context.Context, arg IncrementFavoriteUseCountParams) error {
	_, err := q.db.Exec(ctx, incrementFavoriteUseCount, arg.ID, arg.UserID)
	return err
}

const isFoodFavorite = `-- name: IsFoodFavorite :one
SELECT EXISTS(SELECT 1 FROM food_favorites WHERE user_id = $1 AND lower(name) = lower($2))
`

type IsFoodFavoriteParams struct {
	UserID string `json:"user_id"`
	Lower  string `json:"lower"`
}

func (q *Queries) IsFoodFavorite(ctx context.Context, arg IsFoodFavoriteParams) (bool, error) {
	row := q.db.QueryRow(ctx, isFoodFavorite, arg.UserID, arg.Lower)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const removeFoodFavorite = `-- name: RemoveFoodFavorite :exec
DELETE FROM food_favorites WHERE id = $1 AND user_id = $2
`

type RemoveFoodFavoriteParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) RemoveFoodFavorite(ctx context.Context, arg RemoveFoodFavoriteParams) error {
	_, err := q.db.Exec(ctx, removeFoodFavorite, arg.ID, arg.UserID)
	return err
}
