// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: food_item.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFoodItem = `-- name: CreateFoodItem :one
INSERT INTO food_items (meal_id, name, calories, protein_g, carbs_g, fat_g, fiber_g, serving_size, source)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, meal_id, name, calories, protein_g, carbs_g, fat_g, fiber_g, serving_size, source
`

type CreateFoodItemParams struct {
	MealID      string         `json:"meal_id"`
	Name        string         `json:"name"`
	Calories    int32          `json:"calories"`
	ProteinG    pgtype.Numeric `json:"protein_g"`
	CarbsG      pgtype.Numeric `json:"carbs_g"`
	FatG        pgtype.Numeric `json:"fat_g"`
	FiberG      pgtype.Numeric `json:"fiber_g"`
	ServingSize *string        `json:"serving_size"`
	Source      string         `json:"source"`
}

func (q *Queries) CreateFoodItem(ctx context.Context, arg CreateFoodItemParams) (FoodItem, error) {
	row := q.db.QueryRow(ctx, createFoodItem,
		arg.MealID,
		arg.Name,
		arg.Calories,
		arg.ProteinG,
		arg.CarbsG,
		arg.FatG,
		arg.FiberG,
		arg.ServingSize,
		arg.Source,
	)
	var i FoodItem
	err := row.Scan(
		&i.ID,
		&i.MealID,
		&i.Name,
		&i.Calories,
		&i.ProteinG,
		&i.CarbsG,
		&i.FatG,
		&i.FiberG,
		&i.ServingSize,
		&i.Source,
	)
	return i, err
}

const deleteFoodItem = `-- name: DeleteFoodItem :exec
DELETE FROM food_items WHERE id = $1
`

func (q *Queries) DeleteFoodItem(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteFoodItem, id)
	return err
}

const getFoodItemsByMeal = `-- name: GetFoodItemsByMeal :many
SELECT id, meal_id, name, calories, protein_g, carbs_g, fat_g, fiber_g, serving_size, source FROM food_items WHERE meal_id = $1 ORDER BY id
`

func (q *Queries) GetFoodItemsByMeal(ctx context.Context, mealID string) ([]FoodItem, error) {
	rows, err := q.db.Query(ctx, getFoodItemsByMeal, mealID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FoodItem
	for rows.Next() {
		var i FoodItem
		if err := rows.Scan(
			&i.ID,
			&i.MealID,
			&i.Name,
			&i.Calories,
			&i.ProteinG,
			&i.CarbsG,
			&i.FatG,
			&i.FiberG,
			&i.ServingSize,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFoodItem = `-- name: UpdateFoodItem :exec
UPDATE food_items
SET name = $1, calories = $2, protein_g = $3, carbs_g = $4, fat_g = $5, fiber_g = $6, serving_size = $7
WHERE id = $8
`

type UpdateFoodItemParams struct {
	Name        string         `json:"name"`
	Calories    int32          `json:"calories"`
	ProteinG    pgtype.Numeric `json:"protein_g"`
	CarbsG      pgtype.Numeric `json:"carbs_g"`
	FatG        pgtype.Numeric `json:"fat_g"`
	FiberG      pgtype.Numeric `json:"fiber_g"`
	ServingSize *string        `json:"serving_size"`
	ID          string         `json:"id"`
}

func (q *Queries) UpdateFoodItem(ctx context.Context, arg UpdateFoodItemParams) error {
	_, err := q.db.Exec(ctx, updateFoodItem,
		arg.Name,
		arg.Calories,
		arg.ProteinG,
		arg.CarbsG,
		arg.FatG,
		arg.FiberG,
		arg.ServingSize,
		arg.ID,
	)
	return err
}
