// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: goals.sql

package sqlc

import (
	"context"
)

const createGoals = `-- name: CreateGoals :one
INSERT INTO user_goals (user_id, objective, diet_plan, fasting_window, daily_calorie_target, daily_protein_g, daily_carbs_g, daily_fat_g)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (user_id) DO UPDATE SET
    objective = $2, diet_plan = $3, fasting_window = $4,
    daily_calorie_target = $5, daily_protein_g = $6, daily_carbs_g = $7, daily_fat_g = $8,
    updated_at = NOW()
RETURNING user_id, objective, diet_plan, fasting_window, daily_calorie_target, daily_protein_g, daily_carbs_g, daily_fat_g, created_at, updated_at
`

type CreateGoalsParams struct {
	UserID             string  `json:"user_id"`
	Objective          string  `json:"objective"`
	DietPlan           string  `json:"diet_plan"`
	FastingWindow      *string `json:"fasting_window"`
	DailyCalorieTarget int32   `json:"daily_calorie_target"`
	DailyProteinG      int32   `json:"daily_protein_g"`
	DailyCarbsG        int32   `json:"daily_carbs_g"`
	DailyFatG          int32   `json:"daily_fat_g"`
}

func (q *Queries) CreateGoals(ctx context.Context, arg CreateGoalsParams) (UserGoal, error) {
	row := q.db.QueryRow(ctx, createGoals,
		arg.UserID,
		arg.Objective,
		arg.DietPlan,
		arg.FastingWindow,
		arg.DailyCalorieTarget,
		arg.DailyProteinG,
		arg.DailyCarbsG,
		arg.DailyFatG,
	)
	var i UserGoal
	err := row.Scan(
		&i.UserID,
		&i.Objective,
		&i.DietPlan,
		&i.FastingWindow,
		&i.DailyCalorieTarget,
		&i.DailyProteinG,
		&i.DailyCarbsG,
		&i.DailyFatG,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGoals = `-- name: GetGoals :one
SELECT user_id, objective, diet_plan, fasting_window, daily_calorie_target, daily_protein_g, daily_carbs_g, daily_fat_g, created_at, updated_at FROM user_goals WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetGoals(ctx context.Context, userID string) (UserGoal, error) {
	row := q.db.QueryRow(ctx, getGoals, userID)
	var i UserGoal
	err := row.Scan(
		&i.UserID,
		&i.Objective,
		&i.DietPlan,
		&i.FastingWindow,
		&i.DailyCalorieTarget,
		&i.DailyProteinG,
		&i.DailyCarbsG,
		&i.DailyFatG,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
