// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: groups.sql

package sqlc

import (
	"context"
	"time"
)

const addGroupMember = `-- name: AddGroupMember :exec
INSERT INTO group_members (group_id, user_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (group_id, user_id) DO NOTHING
`

type AddGroupMemberParams struct {
	GroupID string `json:"group_id"`
	UserID  string `json:"user_id"`
	Role    string `json:"role"`
}

func (q *Queries) AddGroupMember(ctx context.Context, arg AddGroupMemberParams) error {
	_, err := q.db.Exec(ctx, addGroupMember, arg.GroupID, arg.UserID, arg.Role)
	return err
}

const createChallenge = `-- name: CreateChallenge :one
INSERT INTO group_challenges (group_id, title, description, metric, target_value, start_date, end_date, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, group_id, title, description, metric, target_value, start_date, end_date, created_by, created_at
`

type CreateChallengeParams struct {
	GroupID     string    `json:"group_id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	Metric      string    `json:"metric"`
	TargetValue int32     `json:"target_value"`
	StartDate   time.Time `json:"start_date"`
	EndDate     time.Time `json:"end_date"`
	CreatedBy   string    `json:"created_by"`
}

func (q *Queries) CreateChallenge(ctx context.Context, arg CreateChallengeParams) (GroupChallenge, error) {
	row := q.db.QueryRow(ctx, createChallenge,
		arg.GroupID,
		arg.Title,
		arg.Description,
		arg.Metric,
		arg.TargetValue,
		arg.StartDate,
		arg.EndDate,
		arg.CreatedBy,
	)
	var i GroupChallenge
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Title,
		&i.Description,
		&i.Metric,
		&i.TargetValue,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (name, description, type, invite_code, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, description, type, invite_code, created_by, created_at
`

type CreateGroupParams struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Type        string `json:"type"`
	InviteCode  string `json:"invite_code"`
	CreatedBy   string `json:"created_by"`
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, createGroup,
		arg.Name,
		arg.Description,
		arg.Type,
		arg.InviteCode,
		arg.CreatedBy,
	)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.InviteCode,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteGroup = `-- name: DeleteGroup :exec
DELETE FROM groups WHERE id = $1 AND created_by = $2
`

type DeleteGroupParams struct {
	ID        string `json:"id"`
	CreatedBy string `json:"created_by"`
}

func (q *Queries) DeleteGroup(ctx context.Context, arg DeleteGroupParams) error {
	_, err := q.db.Exec(ctx, deleteGroup, arg.ID, arg.CreatedBy)
	return err
}

const getGroupByID = `-- name: GetGroupByID :one
SELECT
    g.id, g.name, g.description, g.type, g.invite_code, g.created_by, g.created_at,
    (SELECT COUNT(*) FROM group_members WHERE group_id = g.id)::int AS member_count,
    COALESCE((SELECT role FROM group_members gm2 WHERE gm2.group_id = g.id AND gm2.user_id = $2), '') AS my_role
FROM groups g
WHERE g.id = $1
`

type GetGroupByIDParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

type GetGroupByIDRow struct {
	ID          string      `json:"id"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
	Type        string      `json:"type"`
	InviteCode  string      `json:"invite_code"`
	CreatedBy   string      `json:"created_by"`
	CreatedAt   time.Time   `json:"created_at"`
	MemberCount int32       `json:"member_count"`
	MyRole      interface{} `json:"my_role"`
}

func (q *Queries) GetGroupByID(ctx context.Context, arg GetGroupByIDParams) (GetGroupByIDRow, error) {
	row := q.db.QueryRow(ctx, getGroupByID, arg.ID, arg.UserID)
	var i GetGroupByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.InviteCode,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.MemberCount,
		&i.MyRole,
	)
	return i, err
}

const getGroupByInviteCode = `-- name: GetGroupByInviteCode :one
SELECT id, name, description, type, invite_code, created_by, created_at FROM groups WHERE invite_code = $1
`

func (q *Queries) GetGroupByInviteCode(ctx context.Context, inviteCode string) (Group, error) {
	row := q.db.QueryRow(ctx, getGroupByInviteCode, inviteCode)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.InviteCode,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getGroupChallenges = `-- name: GetGroupChallenges :many
SELECT id, group_id, title, description, metric, target_value, start_date, end_date, created_by, created_at FROM group_challenges WHERE group_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetGroupChallenges(ctx context.Context, groupID string) ([]GroupChallenge, error) {
	rows, err := q.db.Query(ctx, getGroupChallenges, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GroupChallenge
	for rows.Next() {
		var i GroupChallenge
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.Title,
			&i.Description,
			&i.Metric,
			&i.TargetValue,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroupsByMember = `-- name: GetGroupsByMember :many
SELECT
    g.id, g.name, g.description, g.type, g.invite_code, g.created_by, g.created_at,
    (SELECT COUNT(*) FROM group_members WHERE group_id = g.id)::int AS member_count,
    gm.role AS my_role
FROM groups g
JOIN group_members gm ON gm.group_id = g.id AND gm.user_id = $1
ORDER BY g.created_at DESC
`

type GetGroupsByMemberRow struct {
	ID          string    `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Type        string    `json:"type"`
	InviteCode  string    `json:"invite_code"`
	CreatedBy   string    `json:"created_by"`
	CreatedAt   time.Time `json:"created_at"`
	MemberCount int32     `json:"member_count"`
	MyRole      string    `json:"my_role"`
}

func (q *Queries) GetGroupsByMember(ctx context.Context, userID string) ([]GetGroupsByMemberRow, error) {
	rows, err := q.db.Query(ctx, getGroupsByMember, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGroupsByMemberRow
	for rows.Next() {
		var i GetGroupsByMemberRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Type,
			&i.InviteCode,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.MemberCount,
			&i.MyRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPublicGroups = `-- name: GetPublicGroups :many
SELECT
    g.id, g.name, g.description,
    (SELECT COUNT(*) FROM group_members WHERE group_id = g.id)::int AS member_count
FROM groups g
WHERE g.type = 'public'
ORDER BY member_count DESC
LIMIT 20
`

type GetPublicGroupsRow struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	MemberCount int32  `json:"member_count"`
}

func (q *Queries) GetPublicGroups(ctx context.Context) ([]GetPublicGroupsRow, error) {
	rows, err := q.db.Query(ctx, getPublicGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPublicGroupsRow
	for rows.Next() {
		var i GetPublicGroupsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.MemberCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserGroupRole = `-- name: GetUserGroupRole :one
SELECT role FROM group_members WHERE group_id = $1 AND user_id = $2
`

type GetUserGroupRoleParams struct {
	GroupID string `json:"group_id"`
	UserID  string `json:"user_id"`
}

func (q *Queries) GetUserGroupRole(ctx context.Context, arg GetUserGroupRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, getUserGroupRole, arg.GroupID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const isGroupMember = `-- name: IsGroupMember :one
SELECT EXISTS(SELECT 1 FROM group_members WHERE group_id = $1 AND user_id = $2) AS is_member
`

type IsGroupMemberParams struct {
	GroupID string `json:"group_id"`
	UserID  string `json:"user_id"`
}

func (q *Queries) IsGroupMember(ctx context.Context, arg IsGroupMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isGroupMember, arg.GroupID, arg.UserID)
	var is_member bool
	err := row.Scan(&is_member)
	return is_member, err
}

const removeGroupMember = `-- name: RemoveGroupMember :exec
DELETE FROM group_members WHERE group_id = $1 AND user_id = $2
`

type RemoveGroupMemberParams struct {
	GroupID string `json:"group_id"`
	UserID  string `json:"user_id"`
}

func (q *Queries) RemoveGroupMember(ctx context.Context, arg RemoveGroupMemberParams) error {
	_, err := q.db.Exec(ctx, removeGroupMember, arg.GroupID, arg.UserID)
	return err
}
