// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: habits.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserStats = `-- name: GetUserStats :one
SELECT user_id, total_points, streak_days, last_active_date, updated_at FROM user_stats WHERE user_id = $1
`

func (q *Queries) GetUserStats(ctx context.Context, userID string) (UserStat, error) {
	row := q.db.QueryRow(ctx, getUserStats, userID)
	var i UserStat
	err := row.Scan(
		&i.UserID,
		&i.TotalPoints,
		&i.StreakDays,
		&i.LastActiveDate,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserStats = `-- name: UpsertUserStats :one
INSERT INTO user_stats (user_id, total_points, streak_days, last_active_date, updated_at)
VALUES ($1, $2, $3, $4, NOW())
ON CONFLICT (user_id) DO UPDATE
    SET total_points = EXCLUDED.total_points,
        streak_days = EXCLUDED.streak_days,
        last_active_date = EXCLUDED.last_active_date,
        updated_at = NOW()
RETURNING user_id, total_points, streak_days, last_active_date, updated_at
`

type UpsertUserStatsParams struct {
	UserID         string      `json:"user_id"`
	TotalPoints    int32       `json:"total_points"`
	StreakDays     int32       `json:"streak_days"`
	LastActiveDate pgtype.Date `json:"last_active_date"`
}

func (q *Queries) UpsertUserStats(ctx context.Context, arg UpsertUserStatsParams) (UserStat, error) {
	row := q.db.QueryRow(ctx, upsertUserStats,
		arg.UserID,
		arg.TotalPoints,
		arg.StreakDays,
		arg.LastActiveDate,
	)
	var i UserStat
	err := row.Scan(
		&i.UserID,
		&i.TotalPoints,
		&i.StreakDays,
		&i.LastActiveDate,
		&i.UpdatedAt,
	)
	return i, err
}
