// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: meal.sql

package sqlc

import (
	"context"
	"time"
)

const createMeal = `-- name: CreateMeal :one
INSERT INTO meals (user_id, timestamp, meal_type, photo_path, note)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, timestamp, meal_type, photo_path, note, created_at
`

type CreateMealParams struct {
	UserID    string    `json:"user_id"`
	Timestamp time.Time `json:"timestamp"`
	MealType  string    `json:"meal_type"`
	PhotoPath *string   `json:"photo_path"`
	Note      *string   `json:"note"`
}

func (q *Queries) CreateMeal(ctx context.Context, arg CreateMealParams) (Meal, error) {
	row := q.db.QueryRow(ctx, createMeal,
		arg.UserID,
		arg.Timestamp,
		arg.MealType,
		arg.PhotoPath,
		arg.Note,
	)
	var i Meal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Timestamp,
		&i.MealType,
		&i.PhotoPath,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMeal = `-- name: DeleteMeal :exec
DELETE FROM meals WHERE id = $1 AND user_id = $2
`

type DeleteMealParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteMeal(ctx context.Context, arg DeleteMealParams) error {
	_, err := q.db.Exec(ctx, deleteMeal, arg.ID, arg.UserID)
	return err
}

const getMealByID = `-- name: GetMealByID :one
SELECT id, user_id, timestamp, meal_type, photo_path, note, created_at FROM meals WHERE id = $1 AND user_id = $2 LIMIT 1
`

type GetMealByIDParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetMealByID(ctx context.Context, arg GetMealByIDParams) (Meal, error) {
	row := q.db.QueryRow(ctx, getMealByID, arg.ID, arg.UserID)
	var i Meal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Timestamp,
		&i.MealType,
		&i.PhotoPath,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const getMealsByDate = `-- name: GetMealsByDate :many
SELECT id, user_id, timestamp, meal_type, photo_path, note, created_at FROM meals
WHERE user_id = $1 AND timestamp::date = $2
ORDER BY timestamp
`

type GetMealsByDateParams struct {
	UserID    string    `json:"user_id"`
	Timestamp time.Time `json:"timestamp"`
}

func (q *Queries) GetMealsByDate(ctx context.Context, arg GetMealsByDateParams) ([]Meal, error) {
	rows, err := q.db.Query(ctx, getMealsByDate, arg.UserID, arg.Timestamp)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Meal
	for rows.Next() {
		var i Meal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Timestamp,
			&i.MealType,
			&i.PhotoPath,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentMeals = `-- name: GetRecentMeals :many
SELECT m.id, m.user_id, m.timestamp, m.meal_type, m.photo_path, m.note, m.created_at FROM meals m
WHERE m.user_id = $1
ORDER BY m.created_at DESC
LIMIT 20
`

func (q *Queries) GetRecentMeals(ctx context.Context, userID string) ([]Meal, error) {
	rows, err := q.db.Query(ctx, getRecentMeals, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Meal
	for rows.Next() {
		var i Meal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Timestamp,
			&i.MealType,
			&i.PhotoPath,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
