// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Achievement struct {
	ID          string    `json:"id"`
	UserID      string    `json:"user_id"`
	Type        string    `json:"type"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	UnlockedAt  time.Time `json:"unlocked_at"`
}

type CoachMessage struct {
	ID        string    `json:"id"`
	UserID    string    `json:"user_id"`
	Role      string    `json:"role"`
	Content   string    `json:"content"`
	CreatedAt time.Time `json:"created_at"`
}

type Exercise struct {
	ID             string    `json:"id"`
	UserID         string    `json:"user_id"`
	Timestamp      time.Time `json:"timestamp"`
	Name           string    `json:"name"`
	DurationMin    int32     `json:"duration_min"`
	CaloriesBurned int32     `json:"calories_burned"`
	CreatedAt      time.Time `json:"created_at"`
}

type FoodItem struct {
	ID          string         `json:"id"`
	MealID      string         `json:"meal_id"`
	Name        string         `json:"name"`
	Calories    int32          `json:"calories"`
	ProteinG    pgtype.Numeric `json:"protein_g"`
	CarbsG      pgtype.Numeric `json:"carbs_g"`
	FatG        pgtype.Numeric `json:"fat_g"`
	FiberG      pgtype.Numeric `json:"fiber_g"`
	ServingSize *string        `json:"serving_size"`
	Source      string         `json:"source"`
}

type Meal struct {
	ID        string    `json:"id"`
	UserID    string    `json:"user_id"`
	Timestamp time.Time `json:"timestamp"`
	MealType  string    `json:"meal_type"`
	PhotoPath *string   `json:"photo_path"`
	Note      *string   `json:"note"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	ID               string    `json:"id"`
	Email            string    `json:"email"`
	PasswordHash     string    `json:"password_hash"`
	VerificationCode *string   `json:"verification_code"`
	Verified         bool      `json:"verified"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}

type UserGoal struct {
	UserID             string    `json:"user_id"`
	Objective          string    `json:"objective"`
	DietPlan           string    `json:"diet_plan"`
	FastingWindow      *string   `json:"fasting_window"`
	DailyCalorieTarget int32     `json:"daily_calorie_target"`
	DailyProteinG      int32     `json:"daily_protein_g"`
	DailyCarbsG        int32     `json:"daily_carbs_g"`
	DailyFatG          int32     `json:"daily_fat_g"`
	CreatedAt          time.Time `json:"created_at"`
	UpdatedAt          time.Time `json:"updated_at"`
}

type UserProfile struct {
	UserID             string         `json:"user_id"`
	Name               string         `json:"name"`
	Age                *int32         `json:"age"`
	Sex                *string        `json:"sex"`
	HeightCm           pgtype.Numeric `json:"height_cm"`
	WeightKg           pgtype.Numeric `json:"weight_kg"`
	TargetWeightKg     pgtype.Numeric `json:"target_weight_kg"`
	ActivityLevel      *string        `json:"activity_level"`
	OnboardingComplete bool           `json:"onboarding_complete"`
	CreatedAt          time.Time      `json:"created_at"`
	UpdatedAt          time.Time      `json:"updated_at"`
}

type WaterLog struct {
	ID        string    `json:"id"`
	UserID    string    `json:"user_id"`
	Date      time.Time `json:"date"`
	AmountMl  int32     `json:"amount_ml"`
	CreatedAt time.Time `json:"created_at"`
}

type WeightLog struct {
	ID        string         `json:"id"`
	UserID    string         `json:"user_id"`
	Date      time.Time      `json:"date"`
	WeightKg  pgtype.Numeric `json:"weight_kg"`
	CreatedAt time.Time      `json:"created_at"`
}
