// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Achievement struct {
	ID              string    `json:"id"`
	UserID          string    `json:"user_id"`
	Type            string    `json:"type"`
	Title           string    `json:"title"`
	Description     string    `json:"description"`
	Category        string    `json:"category"`
	ProgressCurrent int32     `json:"progress_current"`
	ProgressTarget  int32     `json:"progress_target"`
	UnlockedAt      time.Time `json:"unlocked_at"`
}

type AppSetting struct {
	Key       string    `json:"key"`
	Value     string    `json:"value"`
	UpdatedAt time.Time `json:"updated_at"`
}

type CheatDay struct {
	UserID string    `json:"user_id"`
	Date   time.Time `json:"date"`
}

type CoachMessage struct {
	ID        string    `json:"id"`
	UserID    string    `json:"user_id"`
	Role      string    `json:"role"`
	Content   string    `json:"content"`
	CreatedAt time.Time `json:"created_at"`
}

type Exercise struct {
	ID             string    `json:"id"`
	UserID         string    `json:"user_id"`
	Timestamp      time.Time `json:"timestamp"`
	Name           string    `json:"name"`
	DurationMin    int32     `json:"duration_min"`
	CaloriesBurned int32     `json:"calories_burned"`
	CreatedAt      time.Time `json:"created_at"`
}

type FoodFavorite struct {
	ID          string         `json:"id"`
	UserID      string         `json:"user_id"`
	Name        string         `json:"name"`
	Calories    int32          `json:"calories"`
	ProteinG    pgtype.Numeric `json:"protein_g"`
	CarbsG      pgtype.Numeric `json:"carbs_g"`
	FatG        pgtype.Numeric `json:"fat_g"`
	FiberG      pgtype.Numeric `json:"fiber_g"`
	ServingSize string         `json:"serving_size"`
	Source      string         `json:"source"`
	UseCount    int32          `json:"use_count"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type FoodItem struct {
	ID          string         `json:"id"`
	MealID      string         `json:"meal_id"`
	Name        string         `json:"name"`
	Calories    int32          `json:"calories"`
	ProteinG    pgtype.Numeric `json:"protein_g"`
	CarbsG      pgtype.Numeric `json:"carbs_g"`
	FatG        pgtype.Numeric `json:"fat_g"`
	FiberG      pgtype.Numeric `json:"fiber_g"`
	ServingSize *string        `json:"serving_size"`
	Source      string         `json:"source"`
}

type GoogleFitToken struct {
	UserID       string    `json:"user_id"`
	AccessToken  string    `json:"access_token"`
	RefreshToken string    `json:"refresh_token"`
	Expiry       time.Time `json:"expiry"`
}

type Group struct {
	ID          string    `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Type        string    `json:"type"`
	InviteCode  string    `json:"invite_code"`
	CreatedBy   string    `json:"created_by"`
	CreatedAt   time.Time `json:"created_at"`
}

type GroupChallenge struct {
	ID          string    `json:"id"`
	GroupID     string    `json:"group_id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	Metric      string    `json:"metric"`
	TargetValue int32     `json:"target_value"`
	StartDate   time.Time `json:"start_date"`
	EndDate     time.Time `json:"end_date"`
	CreatedBy   string    `json:"created_by"`
	CreatedAt   time.Time `json:"created_at"`
}

type GroupMember struct {
	GroupID  string    `json:"group_id"`
	UserID   string    `json:"user_id"`
	Role     string    `json:"role"`
	JoinedAt time.Time `json:"joined_at"`
}

type Meal struct {
	ID        string    `json:"id"`
	UserID    string    `json:"user_id"`
	Timestamp time.Time `json:"timestamp"`
	MealType  string    `json:"meal_type"`
	PhotoPath *string   `json:"photo_path"`
	Note      *string   `json:"note"`
	CreatedAt time.Time `json:"created_at"`
}

type NotificationPreference struct {
	UserID             string    `json:"user_id"`
	WaterReminders     bool      `json:"water_reminders"`
	WaterIntervalHours int32     `json:"water_interval_hours"`
	MealReminders      bool      `json:"meal_reminders"`
	IfWindowReminders  bool      `json:"if_window_reminders"`
	StreakReminders    bool      `json:"streak_reminders"`
	QuietStart         int32     `json:"quiet_start"`
	QuietEnd           int32     `json:"quiet_end"`
	NtfyTopic          string    `json:"ntfy_topic"`
	UpdatedAt          time.Time `json:"updated_at"`
}

type NutritionCache struct {
	ID          string         `json:"id"`
	Query       string         `json:"query"`
	Name        string         `json:"name"`
	Calories    int32          `json:"calories"`
	ProteinG    pgtype.Numeric `json:"protein_g"`
	CarbsG      pgtype.Numeric `json:"carbs_g"`
	FatG        pgtype.Numeric `json:"fat_g"`
	FiberG      pgtype.Numeric `json:"fiber_g"`
	ServingSize string         `json:"serving_size"`
	Source      string         `json:"source"`
	CreatedAt   time.Time      `json:"created_at"`
}

type PushSubscription struct {
	ID        string    `json:"id"`
	UserID    string    `json:"user_id"`
	Endpoint  string    `json:"endpoint"`
	P256dh    string    `json:"p256dh"`
	Auth      string    `json:"auth"`
	UserAgent string    `json:"user_agent"`
	CreatedAt time.Time `json:"created_at"`
}

type StepLog struct {
	UserID    string    `json:"user_id"`
	Date      time.Time `json:"date"`
	StepCount int32     `json:"step_count"`
	Source    string    `json:"source"`
}

type User struct {
	ID               string    `json:"id"`
	Email            string    `json:"email"`
	PasswordHash     string    `json:"password_hash"`
	VerificationCode *string   `json:"verification_code"`
	Verified         bool      `json:"verified"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
	IsAdmin          bool      `json:"is_admin"`
	Approved         bool      `json:"approved"`
}

type UserGoal struct {
	UserID             string             `json:"user_id"`
	Objective          string             `json:"objective"`
	DietPlan           string             `json:"diet_plan"`
	FastingWindow      *string            `json:"fasting_window"`
	DailyCalorieTarget int32              `json:"daily_calorie_target"`
	DailyProteinG      int32              `json:"daily_protein_g"`
	DailyCarbsG        int32              `json:"daily_carbs_g"`
	DailyFatG          int32              `json:"daily_fat_g"`
	EatingWindowStart  pgtype.Time        `json:"eating_window_start"`
	CurrentFastStart   pgtype.Timestamptz `json:"current_fast_start"`
	FastingStreak      *int32             `json:"fasting_streak"`
	CreatedAt          time.Time          `json:"created_at"`
	UpdatedAt          time.Time          `json:"updated_at"`
}

type UserPreference struct {
	UserID        string    `json:"user_id"`
	DietType      string    `json:"diet_type"`
	Allergies     []string  `json:"allergies"`
	FoodNotes     string    `json:"food_notes"`
	EatingContext string    `json:"eating_context"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type UserProfile struct {
	UserID             string         `json:"user_id"`
	Name               string         `json:"name"`
	Age                *int32         `json:"age"`
	Sex                *string        `json:"sex"`
	HeightCm           pgtype.Numeric `json:"height_cm"`
	WeightKg           pgtype.Numeric `json:"weight_kg"`
	TargetWeightKg     pgtype.Numeric `json:"target_weight_kg"`
	ActivityLevel      *string        `json:"activity_level"`
	OnboardingComplete bool           `json:"onboarding_complete"`
	CreatedAt          time.Time      `json:"created_at"`
	UpdatedAt          time.Time      `json:"updated_at"`
}

type UserStat struct {
	UserID         string      `json:"user_id"`
	TotalPoints    int32       `json:"total_points"`
	StreakDays     int32       `json:"streak_days"`
	LastActiveDate pgtype.Date `json:"last_active_date"`
	UpdatedAt      time.Time   `json:"updated_at"`
}

type WaterLog struct {
	ID        string    `json:"id"`
	UserID    string    `json:"user_id"`
	Date      time.Time `json:"date"`
	AmountMl  int32     `json:"amount_ml"`
	CreatedAt time.Time `json:"created_at"`
}

type WeightLog struct {
	ID        string         `json:"id"`
	UserID    string         `json:"user_id"`
	Date      time.Time      `json:"date"`
	WeightKg  pgtype.Numeric `json:"weight_kg"`
	CreatedAt time.Time      `json:"created_at"`
}
