// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package sqlc

import (
	"context"
)

const deletePushSubscription = `-- name: DeletePushSubscription :exec
DELETE FROM push_subscriptions WHERE endpoint = $1 AND user_id = $2
`

type DeletePushSubscriptionParams struct {
	Endpoint string `json:"endpoint"`
	UserID   string `json:"user_id"`
}

func (q *Queries) DeletePushSubscription(ctx context.Context, arg DeletePushSubscriptionParams) error {
	_, err := q.db.Exec(ctx, deletePushSubscription, arg.Endpoint, arg.UserID)
	return err
}

const deletePushSubscriptionByEndpoint = `-- name: DeletePushSubscriptionByEndpoint :exec
DELETE FROM push_subscriptions WHERE endpoint = $1
`

func (q *Queries) DeletePushSubscriptionByEndpoint(ctx context.Context, endpoint string) error {
	_, err := q.db.Exec(ctx, deletePushSubscriptionByEndpoint, endpoint)
	return err
}

const getAllUsersWithPushSubscriptions = `-- name: GetAllUsersWithPushSubscriptions :many
SELECT DISTINCT user_id FROM push_subscriptions
`

func (q *Queries) GetAllUsersWithPushSubscriptions(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, getAllUsersWithPushSubscriptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var user_id string
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNotificationPrefs = `-- name: GetNotificationPrefs :one
SELECT user_id, water_reminders, water_interval_hours, meal_reminders, if_window_reminders, streak_reminders, quiet_start, quiet_end, ntfy_topic, updated_at FROM notification_preferences WHERE user_id = $1
`

func (q *Queries) GetNotificationPrefs(ctx context.Context, userID string) (NotificationPreference, error) {
	row := q.db.QueryRow(ctx, getNotificationPrefs, userID)
	var i NotificationPreference
	err := row.Scan(
		&i.UserID,
		&i.WaterReminders,
		&i.WaterIntervalHours,
		&i.MealReminders,
		&i.IfWindowReminders,
		&i.StreakReminders,
		&i.QuietStart,
		&i.QuietEnd,
		&i.NtfyTopic,
		&i.UpdatedAt,
	)
	return i, err
}

const getPushSubscriptionsByUser = `-- name: GetPushSubscriptionsByUser :many
SELECT id, user_id, endpoint, p256dh, auth, user_agent, created_at FROM push_subscriptions WHERE user_id = $1
`

func (q *Queries) GetPushSubscriptionsByUser(ctx context.Context, userID string) ([]PushSubscription, error) {
	rows, err := q.db.Query(ctx, getPushSubscriptionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PushSubscription
	for rows.Next() {
		var i PushSubscription
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Endpoint,
			&i.P256dh,
			&i.Auth,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const savePushSubscription = `-- name: SavePushSubscription :exec
INSERT INTO push_subscriptions (user_id, endpoint, p256dh, auth, user_agent)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (endpoint) DO UPDATE SET
    p256dh = EXCLUDED.p256dh,
    auth = EXCLUDED.auth,
    user_agent = EXCLUDED.user_agent
`

type SavePushSubscriptionParams struct {
	UserID    string `json:"user_id"`
	Endpoint  string `json:"endpoint"`
	P256dh    string `json:"p256dh"`
	Auth      string `json:"auth"`
	UserAgent string `json:"user_agent"`
}

func (q *Queries) SavePushSubscription(ctx context.Context, arg SavePushSubscriptionParams) error {
	_, err := q.db.Exec(ctx, savePushSubscription,
		arg.UserID,
		arg.Endpoint,
		arg.P256dh,
		arg.Auth,
		arg.UserAgent,
	)
	return err
}

const upsertNotificationPrefs = `-- name: UpsertNotificationPrefs :one
INSERT INTO notification_preferences (user_id, water_reminders, water_interval_hours, meal_reminders, if_window_reminders, streak_reminders, quiet_start, quiet_end, ntfy_topic)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (user_id) DO UPDATE SET
    water_reminders = EXCLUDED.water_reminders,
    water_interval_hours = EXCLUDED.water_interval_hours,
    meal_reminders = EXCLUDED.meal_reminders,
    if_window_reminders = EXCLUDED.if_window_reminders,
    streak_reminders = EXCLUDED.streak_reminders,
    quiet_start = EXCLUDED.quiet_start,
    quiet_end = EXCLUDED.quiet_end,
    ntfy_topic = EXCLUDED.ntfy_topic,
    updated_at = NOW()
RETURNING user_id, water_reminders, water_interval_hours, meal_reminders, if_window_reminders, streak_reminders, quiet_start, quiet_end, ntfy_topic, updated_at
`

type UpsertNotificationPrefsParams struct {
	UserID             string `json:"user_id"`
	WaterReminders     bool   `json:"water_reminders"`
	WaterIntervalHours int32  `json:"water_interval_hours"`
	MealReminders      bool   `json:"meal_reminders"`
	IfWindowReminders  bool   `json:"if_window_reminders"`
	StreakReminders    bool   `json:"streak_reminders"`
	QuietStart         int32  `json:"quiet_start"`
	QuietEnd           int32  `json:"quiet_end"`
	NtfyTopic          string `json:"ntfy_topic"`
}

func (q *Queries) UpsertNotificationPrefs(ctx context.Context, arg UpsertNotificationPrefsParams) (NotificationPreference, error) {
	row := q.db.QueryRow(ctx, upsertNotificationPrefs,
		arg.UserID,
		arg.WaterReminders,
		arg.WaterIntervalHours,
		arg.MealReminders,
		arg.IfWindowReminders,
		arg.StreakReminders,
		arg.QuietStart,
		arg.QuietEnd,
		arg.NtfyTopic,
	)
	var i NotificationPreference
	err := row.Scan(
		&i.UserID,
		&i.WaterReminders,
		&i.WaterIntervalHours,
		&i.MealReminders,
		&i.IfWindowReminders,
		&i.StreakReminders,
		&i.QuietStart,
		&i.QuietEnd,
		&i.NtfyTopic,
		&i.UpdatedAt,
	)
	return i, err
}
