// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: nutrition_cache.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getNutritionCache = `-- name: GetNutritionCache :one
SELECT id, query, name, calories, protein_g, carbs_g, fat_g, fiber_g, serving_size, source, created_at FROM nutrition_cache WHERE lower(query) = lower($1) LIMIT 1
`

func (q *Queries) GetNutritionCache(ctx context.Context, lower string) (NutritionCache, error) {
	row := q.db.QueryRow(ctx, getNutritionCache, lower)
	var i NutritionCache
	err := row.Scan(
		&i.ID,
		&i.Query,
		&i.Name,
		&i.Calories,
		&i.ProteinG,
		&i.CarbsG,
		&i.FatG,
		&i.FiberG,
		&i.ServingSize,
		&i.Source,
		&i.CreatedAt,
	)
	return i, err
}

const upsertNutritionCache = `-- name: UpsertNutritionCache :one
INSERT INTO nutrition_cache (query, name, calories, protein_g, carbs_g, fat_g, fiber_g, serving_size, source)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (lower(query)) DO UPDATE SET
    name = EXCLUDED.name,
    calories = EXCLUDED.calories,
    protein_g = EXCLUDED.protein_g,
    carbs_g = EXCLUDED.carbs_g,
    fat_g = EXCLUDED.fat_g,
    fiber_g = EXCLUDED.fiber_g,
    serving_size = EXCLUDED.serving_size,
    source = EXCLUDED.source,
    created_at = NOW()
RETURNING id, query, name, calories, protein_g, carbs_g, fat_g, fiber_g, serving_size, source, created_at
`

type UpsertNutritionCacheParams struct {
	Query       string         `json:"query"`
	Name        string         `json:"name"`
	Calories    int32          `json:"calories"`
	ProteinG    pgtype.Numeric `json:"protein_g"`
	CarbsG      pgtype.Numeric `json:"carbs_g"`
	FatG        pgtype.Numeric `json:"fat_g"`
	FiberG      pgtype.Numeric `json:"fiber_g"`
	ServingSize string         `json:"serving_size"`
	Source      string         `json:"source"`
}

func (q *Queries) UpsertNutritionCache(ctx context.Context, arg UpsertNutritionCacheParams) (NutritionCache, error) {
	row := q.db.QueryRow(ctx, upsertNutritionCache,
		arg.Query,
		arg.Name,
		arg.Calories,
		arg.ProteinG,
		arg.CarbsG,
		arg.FatG,
		arg.FiberG,
		arg.ServingSize,
		arg.Source,
	)
	var i NutritionCache
	err := row.Scan(
		&i.ID,
		&i.Query,
		&i.Name,
		&i.Calories,
		&i.ProteinG,
		&i.CarbsG,
		&i.FatG,
		&i.FiberG,
		&i.ServingSize,
		&i.Source,
		&i.CreatedAt,
	)
	return i, err
}
