// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: profile.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeOnboarding = `-- name: CompleteOnboarding :exec
UPDATE user_profiles SET onboarding_complete = TRUE, updated_at = NOW() WHERE user_id = $1
`

func (q *Queries) CompleteOnboarding(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, completeOnboarding, userID)
	return err
}

const createProfile = `-- name: CreateProfile :one
INSERT INTO user_profiles (user_id, name, age, sex, height_cm, weight_kg, target_weight_kg, activity_level, onboarding_complete)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING user_id, name, age, sex, height_cm, weight_kg, target_weight_kg, activity_level, onboarding_complete, created_at, updated_at
`

type CreateProfileParams struct {
	UserID             string         `json:"user_id"`
	Name               string         `json:"name"`
	Age                *int32         `json:"age"`
	Sex                *string        `json:"sex"`
	HeightCm           pgtype.Numeric `json:"height_cm"`
	WeightKg           pgtype.Numeric `json:"weight_kg"`
	TargetWeightKg     pgtype.Numeric `json:"target_weight_kg"`
	ActivityLevel      *string        `json:"activity_level"`
	OnboardingComplete bool           `json:"onboarding_complete"`
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) (UserProfile, error) {
	row := q.db.QueryRow(ctx, createProfile,
		arg.UserID,
		arg.Name,
		arg.Age,
		arg.Sex,
		arg.HeightCm,
		arg.WeightKg,
		arg.TargetWeightKg,
		arg.ActivityLevel,
		arg.OnboardingComplete,
	)
	var i UserProfile
	err := row.Scan(
		&i.UserID,
		&i.Name,
		&i.Age,
		&i.Sex,
		&i.HeightCm,
		&i.WeightKg,
		&i.TargetWeightKg,
		&i.ActivityLevel,
		&i.OnboardingComplete,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProfile = `-- name: GetProfile :one
SELECT user_id, name, age, sex, height_cm, weight_kg, target_weight_kg, activity_level, onboarding_complete, created_at, updated_at FROM user_profiles WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetProfile(ctx context.Context, userID string) (UserProfile, error) {
	row := q.db.QueryRow(ctx, getProfile, userID)
	var i UserProfile
	err := row.Scan(
		&i.UserID,
		&i.Name,
		&i.Age,
		&i.Sex,
		&i.HeightCm,
		&i.WeightKg,
		&i.TargetWeightKg,
		&i.ActivityLevel,
		&i.OnboardingComplete,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProfile = `-- name: UpdateProfile :exec
UPDATE user_profiles
SET name = $2, age = $3, sex = $4, height_cm = $5, weight_kg = $6, target_weight_kg = $7, activity_level = $8, updated_at = NOW()
WHERE user_id = $1
`

type UpdateProfileParams struct {
	UserID         string         `json:"user_id"`
	Name           string         `json:"name"`
	Age            *int32         `json:"age"`
	Sex            *string        `json:"sex"`
	HeightCm       pgtype.Numeric `json:"height_cm"`
	WeightKg       pgtype.Numeric `json:"weight_kg"`
	TargetWeightKg pgtype.Numeric `json:"target_weight_kg"`
	ActivityLevel  *string        `json:"activity_level"`
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) error {
	_, err := q.db.Exec(ctx, updateProfile,
		arg.UserID,
		arg.Name,
		arg.Age,
		arg.Sex,
		arg.HeightCm,
		arg.WeightKg,
		arg.TargetWeightKg,
		arg.ActivityLevel,
	)
	return err
}
