// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: steps.sql

package sqlc

import (
	"context"
	"time"
)

const getStepsByDate = `-- name: GetStepsByDate :one
SELECT user_id, date, step_count, source
FROM step_logs
WHERE user_id = $1 AND date = $2
`

type GetStepsByDateParams struct {
	UserID string    `json:"user_id"`
	Date   time.Time `json:"date"`
}

func (q *Queries) GetStepsByDate(ctx context.Context, arg GetStepsByDateParams) (StepLog, error) {
	row := q.db.QueryRow(ctx, getStepsByDate, arg.UserID, arg.Date)
	var i StepLog
	err := row.Scan(
		&i.UserID,
		&i.Date,
		&i.StepCount,
		&i.Source,
	)
	return i, err
}

const getStepsHistory = `-- name: GetStepsHistory :many
SELECT user_id, date, step_count, source
FROM step_logs
WHERE user_id = $1 AND date >= $2 AND date <= $3
ORDER BY date ASC
`

type GetStepsHistoryParams struct {
	UserID string    `json:"user_id"`
	Date   time.Time `json:"date"`
	Date_2 time.Time `json:"date_2"`
}

func (q *Queries) GetStepsHistory(ctx context.Context, arg GetStepsHistoryParams) ([]StepLog, error) {
	rows, err := q.db.Query(ctx, getStepsHistory, arg.UserID, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StepLog
	for rows.Next() {
		var i StepLog
		if err := rows.Scan(
			&i.UserID,
			&i.Date,
			&i.StepCount,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const logSteps = `-- name: LogSteps :one
INSERT INTO step_logs (user_id, date, step_count, source)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, date) DO UPDATE
    SET step_count = EXCLUDED.step_count,
        source = EXCLUDED.source
RETURNING user_id, date, step_count, source
`

type LogStepsParams struct {
	UserID    string    `json:"user_id"`
	Date      time.Time `json:"date"`
	StepCount int32     `json:"step_count"`
	Source    string    `json:"source"`
}

func (q *Queries) LogSteps(ctx context.Context, arg LogStepsParams) (StepLog, error) {
	row := q.db.QueryRow(ctx, logSteps,
		arg.UserID,
		arg.Date,
		arg.StepCount,
		arg.Source,
	)
	var i StepLog
	err := row.Scan(
		&i.UserID,
		&i.Date,
		&i.StepCount,
		&i.Source,
	)
	return i, err
}
