// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: water.sql

package sqlc

import (
	"context"
	"time"
)

const getWaterByDate = `-- name: GetWaterByDate :one
SELECT COALESCE(SUM(amount_ml), 0)::int AS total
FROM water_logs
WHERE user_id = $1 AND date = $2
`

type GetWaterByDateParams struct {
	UserID string    `json:"user_id"`
	Date   time.Time `json:"date"`
}

func (q *Queries) GetWaterByDate(ctx context.Context, arg GetWaterByDateParams) (int32, error) {
	row := q.db.QueryRow(ctx, getWaterByDate, arg.UserID, arg.Date)
	var total int32
	err := row.Scan(&total)
	return total, err
}

const logWater = `-- name: LogWater :one
INSERT INTO water_logs (user_id, date, amount_ml)
VALUES ($1, $2, $3)
RETURNING id, user_id, date, amount_ml, created_at
`

type LogWaterParams struct {
	UserID   string    `json:"user_id"`
	Date     time.Time `json:"date"`
	AmountMl int32     `json:"amount_ml"`
}

func (q *Queries) LogWater(ctx context.Context, arg LogWaterParams) (WaterLog, error) {
	row := q.db.QueryRow(ctx, logWater, arg.UserID, arg.Date, arg.AmountMl)
	var i WaterLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Date,
		&i.AmountMl,
		&i.CreatedAt,
	)
	return i, err
}
