// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: weight.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const getWeightHistory = `-- name: GetWeightHistory :many
SELECT id, user_id, date, weight_kg, created_at FROM weight_logs
WHERE user_id = $1 AND date BETWEEN $2 AND $3
ORDER BY date
`

type GetWeightHistoryParams struct {
	UserID string    `json:"user_id"`
	Date   time.Time `json:"date"`
	Date_2 time.Time `json:"date_2"`
}

func (q *Queries) GetWeightHistory(ctx context.Context, arg GetWeightHistoryParams) ([]WeightLog, error) {
	rows, err := q.db.Query(ctx, getWeightHistory, arg.UserID, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WeightLog
	for rows.Next() {
		var i WeightLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Date,
			&i.WeightKg,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const logWeight = `-- name: LogWeight :one
INSERT INTO weight_logs (user_id, date, weight_kg)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, date) DO UPDATE SET weight_kg = $3, created_at = NOW()
RETURNING id, user_id, date, weight_kg, created_at
`

type LogWeightParams struct {
	UserID   string         `json:"user_id"`
	Date     time.Time      `json:"date"`
	WeightKg pgtype.Numeric `json:"weight_kg"`
}

func (q *Queries) LogWeight(ctx context.Context, arg LogWeightParams) (WeightLog, error) {
	row := q.db.QueryRow(ctx, logWeight, arg.UserID, arg.Date, arg.WeightKg)
	var i WeightLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Date,
		&i.WeightKg,
		&i.CreatedAt,
	)
	return i, err
}
